version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 200
      runas: centos
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 200
      runas: centos
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 200
      runas: centos